### ISSUE TITLE
Make it possible to change TODO message format

### ISSUE THREAD

**Issue by Prifiz** [s3rius/pre_commit_hooks#2]
In this hook https://github.com/s3rius/pre_commit_hooks#todos-linked-to-a-jira-ticket,
it would be great to configure TODO messages formats. E.g. sometimes it is needed to forbid not only TODO but also FIXME or something else in commit content.

**Comment by s3rius** [comment]
Do you mean the prefix for linked comments pattern?

```
# TODO MEME-123: do smth
# FIXME MEME-123: fix smth
```
or both?

**Comment by Prifiz** [comment]
I mean different ones which the developer can configure in hook settings. E.g. the custom one can exist like //MYSHITTYCODE

**Comment by s3rius** [comment]
Added arguments for different todo formats. Problem closed.
