### ISSUE TITLE
Hook to find swear words in comments

### ISSUE THREAD

**Issue by Prifiz** [s3rius/pre_commit_hooks#3]
Sometimes developers like writing different unappropriate words or phrases in comments.
It would be useful to find them and make the developers to remove word/phrases like "f*ck", "sh*t", etc. because sometimes sources can be shared with the others...

**Comment by s3rius** [comment]
How should I add this? 
I have an option to add hook where you can add your very own profanity words, but I don't really sure that this is a good solution.
Maybe I can add  implicit dictionaries for several languages and add languages as a parameters.

**Comment by Prifiz** [comment]
The second approach would be better.
And one should be able to specity the exceptions. E.g. the Spanish word "puta" is a part of the very often used names "comPUTAtional" or "PUTAll" of variables or methods which may be referenced in comments.

**Comment by s3rius** [comment]
I think that better thin is to add flags in code to ignore some lines. 
Like if we have `noqa: profanity` string on the line with profanity, we can skip this line.

Also, I don't think, that checking for substring without spaces around the word is a good idea.

**Comment by Kolaer** [comment]
I don't think that there is a need for a programming solution for this problem. Most of the time something like contribution guide/code review/mention in the readme is enough.
And if a second approach would be chosen, then it'll drastically increase code size (dictionary/ml model/... for every language).

**Comment by s3rius** [comment]
@Kolaer, I agree. Libraries such as [profanity-check](https://github.com/vzhou842/profanity-check) need to install 100+ Mb of dictionaries or ML models. And we don't really need it. Because, as was mentioned previously, you can easily spot profanity words during the review.

Feature declined.
